USE FINANCE_MANAGER;

DELIMITER $

DROP PROCEDURE IF EXISTS ADDOPERATION;

CREATE PROCEDURE ADDOPERATION (
  OPDATE DATE,
  OPDESCRIPTION VARCHAR(150),
  OPCATEGORY INT,
  OPINCOME FLOAT,
  OPDEBIT FLOAT
) 
BEGIN
  DECLARE PREVBALANCE FLOAT;

  -- GET PREVIOUS BALANCE
  SELECT BALANCE INTO PREVBALANCE 
  FROM OPERATIONS
  ORDER BY DATE DESC, ID DESC
  LIMIT 1;

  INSERT INTO
    OPERATIONS (
      DATE,
      DESCRIPTION,
      CATEGORY,
      INCOME,
      DEBIT,
      BALANCE
    )
  VALUES
    (
      OPDATE, 
      OPDESCRIPTION, 
      OPCATEGORY, 
      OPINCOME, 
      OPDEBIT, 
      PREVBALANCE + OPINCOME - OPDEBIT
    );
END$

DELIMITER ;
